### ISSUE TITLE
ContentCreator.php

### ISSUE THREAD

**Issue by gabrielcontessotto** [bramley/phplist-plugin-viewbrowser#12]
Hi, 

I installed the plugin by Manage Plugin, set the PlaceHold VIEWBROWSER but when i click on link i got this message..

*/ViewBrowserPlugin/ContentCreator.php on line 322*
*phpList version 3.2.0*

I already try copy the file view_3.0.6.php to view.php to my root folder.

*/var/www/list/view.php*

*NameView in Browser plugin
version2.4.3+20151215
DescriptionNo description
installed2016-01-19
installation Urlhttps://github.com/bramley/phplist-plugin-viewbrowser/archive/master.zip
Developerbramley*

thanks for any help

**Comment by bramley** [comment]
I don't understand the message that you have tried to copy, as it seems to be incomplete. Please can copy the complete message or take a screenshot and include that.

    ViewBrowserPlugin/ContentCreator.php on line 322

I would expect the complete file path, something like "/var/www/lists/.... "
The line number in the message looks odd because it refers to a blank line.

**Comment by gabrielcontessotto** [comment]
Sorry for that, this is the full message:

*PHP Fatal error:  Call to undefined function phpList\\plugin\\ViewBrowserPlugin\\parseLogoPlaceholders() in /var/www/sartorfotografianews.informaticagt.com.br/admin/plugins/ViewBrowserPlugin/ContentCreator.php on line 320*

The line 322 its cause i try change some thing or other... 

Now i full remove the plugin install again e got this clean message. 

Thanks...

**Comment by bramley** [comment]
There is a mistake in the plugin documentation because it now requires phplist 3.2.2 or later. You are using release 3.2.0 so you need to install the latest release of phplist.
You could try just deleting line 320 from the file ContentCreator.php to see whether that works, but I recommend upgrading phplist anyway

        $content = parseLogoPlaceholders($content);

**Comment by gabrielcontessotto** [comment]
Ok, i WILL upgrade my Phplist, Thanks.

Just for the record... 

I comment the *320 line* and work. 

*//        $content = parseLogoPlaceholders($content);*

Thank you again for your help
